#include "shaderlib/cshader.h"
class cryostasis_magichdr_inverse_ps20b_Static_Index
{
public:
	cryostasis_magichdr_inverse_ps20b_Static_Index()
	{
	}
	int GetIndex()
	{
		return 0;
	}
};
#define shaderStaticTest_cryostasis_magichdr_inverse_ps20b 0
class cryostasis_magichdr_inverse_ps20b_Dynamic_Index
{
public:
	cryostasis_magichdr_inverse_ps20b_Dynamic_Index()
	{
	}
	int GetIndex()
	{
		return 0;
	}
};
#define shaderDynamicTest_cryostasis_magichdr_inverse_ps20b 0
